name: Revision de Codigo Python (CI)

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Revisar errores de sintaxis
        run: python -m py_compile main.py logica/*.py vistas/*.py